# sudo: false
language: node_js

os: osx

node_js:
  - 14.16.0 # use nodejs v10 LTS

cache: 
  directories:
    - node_modules

branches:
  only:
    - master # build master branch only

script:
  - hexo g -d # generate static files

# deploy:
#   provider: pages
#   skip_cleanup: true
#   token: $GH_TOKEN
#   keep_history: true
#   on:
#     branch: master
#   local_dir: public
