# sudo: false
language: node_js

os: osx

node_js:
  - 14.16.0 # use nodejs v10 LTS

cache: 
  directories:
    - node_modules

branches:
  only:
    - master # build master branch only

before_install:
- openssl aes-256-cbc -K $encrypted_15db670b9b95_key -iv $encrypted_15db670b9b95_iv -in .travis/id_rsa_travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "keleyundou"
- git config --global user.email colabean720@gmail.com

script:
  - hexo g -d # generate static files

# deploy:
#   provider: pages
#   skip_cleanup: true
#   token: $GH_TOKEN
#   keep_history: true
#   on:
#     branch: master
#   local_dir: public
