# sudo: false
language: node_js
node_js:
  - stable # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: gh-pages
  local_dir: public
